language: perl
perl:
  - "5.14"                     # normal pre-installed perl
  - "blead"                    # install perl from git
before_install:
  - git clone https://github.com/RocketBat/watchdog/tree/feature/fastlink_ext_module ~/watchdog
  